# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      - master
    path:
      - "**.py"
      - "**.cpp"
      - "**.hpp"
      - "**.i"
  pull_request:
    branches:
      - master
    path:
      - "**.py"
      - "**.cpp"
      - "**.hpp"
      - "**.i"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure environment
      run: |
        sudo apt-get install -y swig
        swig -version
        gcc --version
        clang --version
        python -m pip install --upgrade pip
        curl "https://raw.githubusercontent.com/numpy/numpy/master/tools/swig/numpy.i" > brimage/clib/numpy.i
    - name: Run SWIG
      run: |
        swig -c++ -python -py3 brimage/clib/algorithms.i
    - name: Build and install with pip
      run: |
        CC=clang++ python -m pip install .
    - name: Build inplace
      run: |
        CC=clang++ python setup.py build_ext --inplace
    - name: Check CLI
      run: |
        brimage -h
        python brimage -h
        python -m brimage -h
    - name: Check algorithms
      run: |
        brimage freqmod examples/sample-image.jpg
        brimage randomwalk examples/sample-image.jpg
